pre-commit:
  commands:
    pdm-lock:
      run: pdm lock --check
    black:
      files: git ls-files
      glob: '*.{py, ipynb}'
      run: black {staged_files}
      stage_fixed: true
    clean-jupyter:
      files: git ls-files
      glob: '*.ipynb'
      run: pdm run jupyter nbconvert --clear-output --inplace {staged_files}
      stage_fixed: true
    ruff:
      files: git ls-files
      glob: '*.py'
      run: pdm run ruff {staged_files} --fix
    mypy:
      glob: '*.py'
      run: pdm run mypy --pretty {staged_files} --ignore-missing-imports
    lychee:
      run: lychee . --suggest --max-concurrency 32 --cache --format detailed --header "accept=*/*"

pre-merge:
  commands:
    black:
      glob: '*.{py, ipynb}'
      run: black {all_files}
      stage_fixed: true
    clean-jupyter:
      glob: '*.ipynb'
      run: pdm run jupyter nbconvert --clear-output --inplace {all_files}
      stage_fixed: true
    ruff:
      glob: '*.py'
      run: pdm run ruff {all_files} --fix
    lychee:
      run: lychee . --suggest --max-concurrency 32 --cache --format detailed --header "accept=*/*"
    pdm-lock:
      run: pdm lock