---
title: "Leeswijzer Data Mining & Exploration"
format: pdf
toc: true
---

# Afkortingen
PDA: Python for Data Analysis
MT: the model thinker

# Les 1 - Introductie
Les 1 heeft vooral een heleboel setup van randvoorwaarden.
Kijk op zn minst even op alle paginas die ik hieronder heb neergezet; in een uurtje zou 
je alles moeten kunnen bekijken en de stukjes die ik aan heb gegeven doorgelezen.

## Libraries en tools:

### pyenv
- management van python versies. 
- [docs](https://github.com/pyenv/pyenv) 
- Lees "what pyenv does", "pyenv does not" en "usage"

### poetry 
- virtual environment management. Alternatief voor pip en conda.
- [docs](https://python-poetry.org/docs/)
- Lees [Basic usage](https://python-poetry.org/docs/basic-usage/) hele pagina en [version constraints](https://python-poetry.org/docs/dependency-specification/)

### git 
- versiemanagement van je code
- Lees de handleiding (git.pdf) in de repo

### pandas
- Data frames. Zou bekend moeten zijn. Als naslag, hoofdstuk 5 en 7 van PDA.

### polars 
- Data frames. [docs]9https://github.com/pola-rs/polars). Blazingly fast dataframes, met een backend in Rust.
- Optioneel, maar aan te raden, vooral voor zwaardere workloads.
- De [user guide](https://pola-rs.github.io/polars-book/user-guide/index.html) geeft een goede introductie.

### loguru 
- logging. 
- Gebruik nooit meer print statements, behalve in je jupyter notebooks. Verder gebruik je altijd loguru in je programmas, tenzij je een hele goede reden hebt.
- [docs](https://loguru.readthedocs.io/en/stable/)

### click 
- command line argument parsing
- [docs](https://click.palletsprojects.com/en/8.1.x/)

### pydantic 
- setting management en dataclasses.
- Hier is een vergelijking met andere opties: [click](https://jackmckew.dev/dataclasses-vs-attrs-vs-pydantic.html). Lees even door, het is een 5 minute read, want pydantic is veel rijker dan settings alleen.

# Les 2: Visualisatie

PDA hoofdstuk 9

# Les 3 - Statistiek

MT: hoofdstuk 3, hoofdstuk 5.

# Les 4: Evaluatie
Dashboarding
[flet.dev](https://flet.dev)

# Les 5: Integratie

# Les 6: Testen, presenteren

# Les 7: Presentaties


